"""Generated DDI-L 3.x lifecycle schema metadata.

Auto-generated from ``schemas/ddi/v3_3/*.xsd`` by
``scripts/generate_schema_definitions.py``. Do not edit by hand.

Re-run::

    python scripts/generate_schema_definitions.py

to regenerate after changing the bundled XSDs.
"""

from typing import Literal, NamedTuple

IdentifiableKind = Literal["Maintainable", "Versionable", "Identifiable"]


class FragmentEntity(NamedTuple):
    """A concrete DDI-L identifiable element declared in the XSDs."""

    name: str
    kind: IdentifiableKind


class FragmentReference(NamedTuple):
    """A ``*Reference`` element name observed in any DDI-L XSD."""

    tag: str


FRAGMENT_GENERATED_ENTITIES: tuple[FragmentEntity, ...] = (
    FragmentEntity(name="Access", kind="Identifiable"),
    FragmentEntity(name="ActionToMinimizeLosses", kind="Identifiable"),
    FragmentEntity(name="AggregationVariables", kind="Identifiable"),
    FragmentEntity(name="ApprovalReview", kind="Versionable"),
    FragmentEntity(name="ApprovalReviewDocument", kind="Versionable"),
    FragmentEntity(name="Archive", kind="Maintainable"),
    FragmentEntity(name="Attribute", kind="Identifiable"),
    FragmentEntity(name="AuthorizedSource", kind="Identifiable"),
    FragmentEntity(name="Category", kind="Versionable"),
    FragmentEntity(name="CategoryGroup", kind="Versionable"),
    FragmentEntity(name="CategoryMap", kind="Versionable"),
    FragmentEntity(name="CategoryScheme", kind="Maintainable"),
    FragmentEntity(name="ClassificationCorrespondenceTable", kind="Versionable"),
    FragmentEntity(name="ClassificationFamily", kind="Maintainable"),
    FragmentEntity(name="ClassificationIndex", kind="Versionable"),
    FragmentEntity(name="ClassificationItem", kind="Versionable"),
    FragmentEntity(name="ClassificationLevel", kind="Versionable"),
    FragmentEntity(name="ClassificationSeries", kind="Versionable"),
    FragmentEntity(name="Code", kind="Identifiable"),
    FragmentEntity(name="CodeList", kind="Maintainable"),
    FragmentEntity(name="CodeListGroup", kind="Versionable"),
    FragmentEntity(name="CodeListScheme", kind="Maintainable"),
    FragmentEntity(name="CognitiveExpertReviewActivity", kind="Versionable"),
    FragmentEntity(name="CognitiveInterviewActivity", kind="Versionable"),
    FragmentEntity(name="CollectionEvent", kind="Identifiable"),
    FragmentEntity(name="CollectionSituation", kind="Identifiable"),
    FragmentEntity(name="Comparison", kind="Maintainable"),
    FragmentEntity(name="ComputationItem", kind="Versionable"),
    FragmentEntity(name="Concept", kind="Versionable"),
    FragmentEntity(name="ConceptGroup", kind="Versionable"),
    FragmentEntity(name="ConceptMap", kind="Versionable"),
    FragmentEntity(name="ConceptScheme", kind="Maintainable"),
    FragmentEntity(name="ConceptualComponent", kind="Maintainable"),
    FragmentEntity(name="ConceptualVariable", kind="Versionable"),
    FragmentEntity(name="ConceptualVariableGroup", kind="Versionable"),
    FragmentEntity(name="ConceptualVariableScheme", kind="Maintainable"),
    FragmentEntity(name="ContentReviewActivity", kind="Versionable"),
    FragmentEntity(name="ControlConstructGroup", kind="Versionable"),
    FragmentEntity(name="ControlConstructScheme", kind="Maintainable"),
    FragmentEntity(name="CoordinateRegion", kind="Identifiable"),
    FragmentEntity(name="DDIInstance", kind="Maintainable"),
    FragmentEntity(name="DDIProfile", kind="Maintainable"),
    FragmentEntity(name="DataCaptureDevelopment", kind="Versionable"),
    FragmentEntity(name="DataCollection", kind="Maintainable"),
    FragmentEntity(name="DataCollectionMethodology", kind="Identifiable"),
    FragmentEntity(name="DataRelationship", kind="Versionable"),
    FragmentEntity(name="DataSet", kind="Versionable"),
    FragmentEntity(name="DefaultAccess", kind="Identifiable"),
    FragmentEntity(name="DevelopmentActivityGroup", kind="Versionable"),
    FragmentEntity(name="DevelopmentActivityScheme", kind="Maintainable"),
    FragmentEntity(name="DevelopmentImplementation", kind="Versionable"),
    FragmentEntity(name="DevelopmentPlan", kind="Versionable"),
    FragmentEntity(name="DevelopmentResults", kind="Versionable"),
    FragmentEntity(name="DevelopmentStep", kind="Versionable"),
    FragmentEntity(name="DeviationFromSampleDesign", kind="Identifiable"),
    FragmentEntity(name="Embargo", kind="Identifiable"),
    FragmentEntity(name="FocusGroupActivity", kind="Versionable"),
    FragmentEntity(name="FundingDocument", kind="Versionable"),
    FragmentEntity(name="GeneralInstruction", kind="Versionable"),
    FragmentEntity(name="GenerationInstruction", kind="Versionable"),
    FragmentEntity(name="GeographicLevel", kind="Identifiable"),
    FragmentEntity(name="GeographicLocation", kind="Versionable"),
    FragmentEntity(name="GeographicLocationGroup", kind="Versionable"),
    FragmentEntity(name="GeographicLocationScheme", kind="Maintainable"),
    FragmentEntity(name="GeographicStructure", kind="Versionable"),
    FragmentEntity(name="GeographicStructureGroup", kind="Versionable"),
    FragmentEntity(name="GeographicStructureScheme", kind="Maintainable"),
    FragmentEntity(name="GrossFileStructure", kind="Identifiable"),
    FragmentEntity(name="GrossRecordStructure", kind="Identifiable"),
    FragmentEntity(name="Group", kind="Maintainable"),
    FragmentEntity(name="IfThenElse", kind="Versionable"),
    FragmentEntity(name="InParameter", kind="Identifiable"),
    FragmentEntity(name="Individual", kind="Versionable"),
    FragmentEntity(name="InformationClassification", kind="Versionable"),
    FragmentEntity(name="Instruction", kind="Versionable"),
    FragmentEntity(name="InstructionGroup", kind="Versionable"),
    FragmentEntity(name="Instrument", kind="Versionable"),
    FragmentEntity(name="InstrumentGroup", kind="Versionable"),
    FragmentEntity(name="InstrumentScheme", kind="Maintainable"),
    FragmentEntity(name="InterviewerInstructionScheme", kind="Maintainable"),
    FragmentEntity(name="ItemMap", kind="Identifiable"),
    FragmentEntity(name="LifecycleEvent", kind="Identifiable"),
    FragmentEntity(name="LocalGroupContent", kind="Maintainable"),
    FragmentEntity(name="LocalHoldingPackage", kind="Maintainable"),
    FragmentEntity(name="LocalResourcePackageContent", kind="Maintainable"),
    FragmentEntity(name="LocalStudyUnitContent", kind="Maintainable"),
    FragmentEntity(name="LocationValue", kind="Identifiable"),
    FragmentEntity(name="LogicalProduct", kind="Maintainable"),
    FragmentEntity(name="LogicalRecord", kind="Identifiable"),
    FragmentEntity(name="Loop", kind="Versionable"),
    FragmentEntity(name="ManagedDateTimeRepresentation", kind="Versionable"),
    FragmentEntity(name="ManagedItemMap", kind="Versionable"),
    FragmentEntity(name="ManagedMissingValuesRepresentation", kind="Versionable"),
    FragmentEntity(name="ManagedNumericRepresentation", kind="Versionable"),
    FragmentEntity(name="ManagedRepresentationGroup", kind="Versionable"),
    FragmentEntity(name="ManagedRepresentationScheme", kind="Maintainable"),
    FragmentEntity(name="ManagedScaleRepresentation", kind="Versionable"),
    FragmentEntity(name="ManagedTextRepresentation", kind="Versionable"),
    FragmentEntity(name="MeasureDefinition", kind="Identifiable"),
    FragmentEntity(name="MeasurementConstruct", kind="Versionable"),
    FragmentEntity(name="MeasurementGroup", kind="Versionable"),
    FragmentEntity(name="MeasurementItem", kind="Versionable"),
    FragmentEntity(name="MeasurementScheme", kind="Maintainable"),
    FragmentEntity(name="Methodology", kind="Versionable"),
    FragmentEntity(name="ModeOfCollection", kind="Identifiable"),
    FragmentEntity(name="NCube", kind="Versionable"),
    FragmentEntity(name="NCubeGroup", kind="Versionable"),
    FragmentEntity(name="NCubeInstance", kind="Versionable"),
    FragmentEntity(name="NCubeScheme", kind="Maintainable"),
    FragmentEntity(name="Organization", kind="Versionable"),
    FragmentEntity(name="OrganizationGroup", kind="Versionable"),
    FragmentEntity(name="OrganizationScheme", kind="Maintainable"),
    FragmentEntity(name="OtherMaterial", kind="Versionable"),
    FragmentEntity(name="OtherMaterialGroup", kind="Versionable"),
    FragmentEntity(name="OtherMaterialScheme", kind="Maintainable"),
    FragmentEntity(name="OutParameter", kind="Identifiable"),
    FragmentEntity(name="PhysicalDataProduct", kind="Maintainable"),
    FragmentEntity(name="PhysicalInstance", kind="Maintainable"),
    FragmentEntity(name="PhysicalInstanceGroup", kind="Maintainable"),
    FragmentEntity(name="PhysicalRecordSegment", kind="Identifiable"),
    FragmentEntity(name="PhysicalStructure", kind="Versionable"),
    FragmentEntity(name="PhysicalStructureGroup", kind="Versionable"),
    FragmentEntity(name="PhysicalStructureScheme", kind="Maintainable"),
    FragmentEntity(name="PretestActivity", kind="Versionable"),
    FragmentEntity(name="ProcessingEvent", kind="Versionable"),
    FragmentEntity(name="ProcessingEventGroup", kind="Versionable"),
    FragmentEntity(name="ProcessingEventScheme", kind="Maintainable"),
    FragmentEntity(name="ProcessingInstructionGroup", kind="Versionable"),
    FragmentEntity(name="ProcessingInstructionScheme", kind="Maintainable"),
    FragmentEntity(name="QualityScheme", kind="Maintainable"),
    FragmentEntity(name="QualityStandard", kind="Versionable"),
    FragmentEntity(name="QualityStandardGroup", kind="Versionable"),
    FragmentEntity(name="QualityStatement", kind="Versionable"),
    FragmentEntity(name="QualityStatementGroup", kind="Versionable"),
    FragmentEntity(name="QuestionBlock", kind="Versionable"),
    FragmentEntity(name="QuestionConstruct", kind="Versionable"),
    FragmentEntity(name="QuestionGrid", kind="Versionable"),
    FragmentEntity(name="QuestionGroup", kind="Versionable"),
    FragmentEntity(name="QuestionItem", kind="Versionable"),
    FragmentEntity(name="QuestionMap", kind="Versionable"),
    FragmentEntity(name="QuestionScheme", kind="Maintainable"),
    FragmentEntity(name="RecordLayout", kind="Versionable"),
    FragmentEntity(name="RecordLayoutGroup", kind="Versionable"),
    FragmentEntity(name="RecordLayoutScheme", kind="Maintainable"),
    FragmentEntity(name="RecordRelationship", kind="Identifiable"),
    FragmentEntity(name="Relation", kind="Versionable"),
    FragmentEntity(name="RepeatUntil", kind="Versionable"),
    FragmentEntity(name="RepeatWhile", kind="Versionable"),
    FragmentEntity(name="RepresentationMap", kind="Versionable"),
    FragmentEntity(name="RepresentedVariable", kind="Versionable"),
    FragmentEntity(name="RepresentedVariableGroup", kind="Versionable"),
    FragmentEntity(name="RepresentedVariableScheme", kind="Maintainable"),
    FragmentEntity(name="ResourcePackage", kind="Maintainable"),
    FragmentEntity(name="Sample", kind="Versionable"),
    FragmentEntity(name="SampleFrame", kind="Versionable"),
    FragmentEntity(name="SampleFrameAccess", kind="Identifiable"),
    FragmentEntity(name="SampleStep", kind="Versionable"),
    FragmentEntity(name="SamplingInformationGroup", kind="Versionable"),
    FragmentEntity(name="SamplingInformationScheme", kind="Maintainable"),
    FragmentEntity(name="SamplingPlan", kind="Versionable"),
    FragmentEntity(name="SamplingProcedure", kind="Identifiable"),
    FragmentEntity(name="SamplingStage", kind="Versionable"),
    FragmentEntity(name="Sequence", kind="Versionable"),
    FragmentEntity(name="SpatialCoverage", kind="Identifiable"),
    FragmentEntity(name="Split", kind="Versionable"),
    FragmentEntity(name="SplitJoin", kind="Versionable"),
    FragmentEntity(name="StandardWeight", kind="Identifiable"),
    FragmentEntity(name="StatementItem", kind="Versionable"),
    FragmentEntity(name="StatisticalClassification", kind="Versionable"),
    FragmentEntity(name="StudyUnit", kind="Maintainable"),
    FragmentEntity(name="SubUniverseClass", kind="Versionable"),
    FragmentEntity(name="TemporalCoverage", kind="Identifiable"),
    FragmentEntity(name="TimeMethod", kind="Identifiable"),
    FragmentEntity(name="TopicalCoverage", kind="Identifiable"),
    FragmentEntity(name="TranslationActivity", kind="Versionable"),
    FragmentEntity(name="UnitType", kind="Versionable"),
    FragmentEntity(name="UnitTypeGroup", kind="Versionable"),
    FragmentEntity(name="UnitTypeScheme", kind="Maintainable"),
    FragmentEntity(name="Universe", kind="Versionable"),
    FragmentEntity(name="UniverseGroup", kind="Versionable"),
    FragmentEntity(name="UniverseMap", kind="Versionable"),
    FragmentEntity(name="UniverseScheme", kind="Maintainable"),
    FragmentEntity(name="Variable", kind="Versionable"),
    FragmentEntity(name="VariableGroup", kind="Versionable"),
    FragmentEntity(name="VariableMap", kind="Versionable"),
    FragmentEntity(name="VariableScheme", kind="Maintainable"),
    FragmentEntity(name="VariableStatistics", kind="Versionable"),
    FragmentEntity(name="Weighting", kind="Versionable"),
    FragmentEntity(name="WeightingMethodology", kind="Versionable"),
)


FRAGMENT_GENERATED_REFERENCES: tuple[FragmentReference, ...] = (
    FragmentReference(tag="AgencyOrganizationReference"),
    FragmentReference(tag="AggregationVariablesReference"),
    FragmentReference(tag="ApprovalReviewDocumentReference"),
    FragmentReference(tag="ApprovalReviewReference"),
    FragmentReference(tag="ArchiveOrganizationReference"),
    FragmentReference(tag="ArchiveReference"),
    FragmentReference(tag="AssignedVariableReference"),
    FragmentReference(tag="AttachmentRegionReference"),
    FragmentReference(tag="AttributeReference"),
    FragmentReference(tag="AuthorizedSourceReference"),
    FragmentReference(tag="AuthorizingAgencyReference"),
    FragmentReference(tag="BasedOnReference"),
    FragmentReference(tag="BasedOnSampleReference"),
    FragmentReference(tag="CategoryGroupReference"),
    FragmentReference(tag="CategoryMapReference"),
    FragmentReference(tag="CategoryReference"),
    FragmentReference(tag="CategorySchemeReference"),
    FragmentReference(tag="ClassificationCorrespondenceTableReference"),
    FragmentReference(tag="ClassificationFamilyReference"),
    FragmentReference(tag="ClassificationIndexReference"),
    FragmentReference(tag="ClassificationItemReference"),
    FragmentReference(tag="ClassificationLevelReference"),
    FragmentReference(tag="ClassificationSeriesReference"),
    FragmentReference(tag="CodeListGroupReference"),
    FragmentReference(tag="CodeListReference"),
    FragmentReference(tag="CodeListSchemeReference"),
    FragmentReference(tag="CodeReference"),
    FragmentReference(tag="CodesClassificationItemReference"),
    FragmentReference(tag="ComparisonReference"),
    FragmentReference(tag="ComplianceConceptReference"),
    FragmentReference(tag="ComponentReference"),
    FragmentReference(tag="ComponentSampleReference"),
    FragmentReference(tag="ConceptGroupReference"),
    FragmentReference(tag="ConceptMapReference"),
    FragmentReference(tag="ConceptReference"),
    FragmentReference(tag="ConceptSchemeReference"),
    FragmentReference(tag="ConceptualComponentReference"),
    FragmentReference(tag="ConceptualVariableGroupReference"),
    FragmentReference(tag="ConceptualVariableReference"),
    FragmentReference(tag="ConceptualVariableSchemeReference"),
    FragmentReference(tag="ConditionalVariableReference"),
    FragmentReference(tag="ContactOrganizationReference"),
    FragmentReference(tag="ContactPersonReference"),
    FragmentReference(tag="ContactReference"),
    FragmentReference(tag="ContributorReference"),
    FragmentReference(tag="ControlConstructGroupReference"),
    FragmentReference(tag="ControlConstructReference"),
    FragmentReference(tag="ControlConstructSchemeReference"),
    FragmentReference(tag="CreatorReference"),
    FragmentReference(tag="CurrentStatisticalClassificationReference"),
    FragmentReference(tag="CustodianReference"),
    FragmentReference(tag="DDIProfileReference"),
    FragmentReference(tag="DataCaptureDevelopmentReference"),
    FragmentReference(tag="DataCollectionReference"),
    FragmentReference(tag="DataCollectorOrganizationReference"),
    FragmentReference(tag="DataRelationshipReference"),
    FragmentReference(tag="DateTimeDomainReference"),
    FragmentReference(tag="DateTimeRepresentationReference"),
    FragmentReference(tag="DefaultDateTimeDataTypeReference"),
    FragmentReference(tag="DefaultMissingValuesReference"),
    FragmentReference(tag="DefaultNumericDataTypeReference"),
    FragmentReference(tag="DefaultTextDataTypeReference"),
    FragmentReference(tag="DefaultVariableSchemeReference"),
    FragmentReference(tag="DefiningCategoryReference"),
    FragmentReference(tag="DefiningConceptReference"),
    FragmentReference(tag="DependentVariableReference"),
    FragmentReference(tag="DepositoryGroupReference"),
    FragmentReference(tag="DepositoryObjectReference"),
    FragmentReference(tag="DepositoryResourcePackageReference"),
    FragmentReference(tag="DepositoryStudyUnitReference"),
    FragmentReference(tag="DerivedFromReference"),
    FragmentReference(tag="DevelopmentActivityGroupReference"),
    FragmentReference(tag="DevelopmentActivityReference"),
    FragmentReference(tag="DevelopmentActivitySchemeReference"),
    FragmentReference(tag="DevelopmentImplementationReference"),
    FragmentReference(tag="DevelopmentPlanReference"),
    FragmentReference(tag="DevelopmentResultsReference"),
    FragmentReference(tag="ElseConstructReference"),
    FragmentReference(tag="EmbargoReference"),
    FragmentReference(tag="EnforcementAgencyOrganizationReference"),
    FragmentReference(tag="EvaluatorReference"),
    FragmentReference(tag="ExcludedClassificationItemReference"),
    FragmentReference(tag="ExcludedGeographicLevelReference"),
    FragmentReference(tag="ExcludedLocationValueReference"),
    FragmentReference(tag="ExcludesConceptReference"),
    FragmentReference(tag="FilterVariableReference"),
    FragmentReference(tag="FundingDocumentReference"),
    FragmentReference(tag="GeneralInstructionReference"),
    FragmentReference(tag="GenerationInstructionReference"),
    FragmentReference(tag="GeographicLayerBaseReference"),
    FragmentReference(tag="GeographicLevelReference"),
    FragmentReference(tag="GeographicLocationGroupReference"),
    FragmentReference(tag="GeographicLocationReference"),
    FragmentReference(tag="GeographicLocationSchemeReference"),
    FragmentReference(tag="GeographicStructureGroupReference"),
    FragmentReference(tag="GeographicStructureReference"),
    FragmentReference(tag="GeographicStructureSchemeReference"),
    FragmentReference(tag="GeographyStructureVariableReference"),
    FragmentReference(tag="GroupReference"),
    FragmentReference(tag="GroupingConceptReference"),
    FragmentReference(tag="GroupingUniverseReference"),
    FragmentReference(tag="HighestLevelReference"),
    FragmentReference(tag="IdentifyingVariableReference"),
    FragmentReference(tag="ImputationReference"),
    FragmentReference(tag="IncludesConceptReference"),
    FragmentReference(tag="IndependentVariableReference"),
    FragmentReference(tag="IndividualReference"),
    FragmentReference(tag="InformationClassificationReference"),
    FragmentReference(tag="InputMeasurementReference"),
    FragmentReference(tag="InputQuestionReference"),
    FragmentReference(tag="InputVariableReference"),
    FragmentReference(tag="InstructionGroupReference"),
    FragmentReference(tag="InstructionReference"),
    FragmentReference(tag="InstrumentGroupReference"),
    FragmentReference(tag="InstrumentReference"),
    FragmentReference(tag="InstrumentSchemeReference"),
    FragmentReference(tag="InterviewerInstructionReference"),
    FragmentReference(tag="InterviewerInstructionSchemeReference"),
    FragmentReference(tag="KeyVariableReference"),
    FragmentReference(tag="LocalGroupContentReference"),
    FragmentReference(tag="LocalHoldingPackageReference"),
    FragmentReference(tag="LocalObjectReference"),
    FragmentReference(tag="LocalResourcePackageContentReference"),
    FragmentReference(tag="LocalStudyUnitContentReference"),
    FragmentReference(tag="LocationValueReference"),
    FragmentReference(tag="LogicalProductReference"),
    FragmentReference(tag="LogicalRecordReference"),
    FragmentReference(tag="LoopVariableReference"),
    FragmentReference(tag="LowestLevelReference"),
    FragmentReference(tag="MaintenanceUnitReference"),
    FragmentReference(tag="ManagedDateTimeRepresentationReference"),
    FragmentReference(tag="ManagedItemMapReference"),
    FragmentReference(tag="ManagedMissingValuesRepresentationReference"),
    FragmentReference(tag="ManagedNumericRepresentationReference"),
    FragmentReference(tag="ManagedRepresentationGroupReference"),
    FragmentReference(tag="ManagedRepresentationReference"),
    FragmentReference(tag="ManagedRepresentationSchemeReference"),
    FragmentReference(tag="ManagedScaleRepresentationReference"),
    FragmentReference(tag="ManagedTextRepresentationReference"),
    FragmentReference(tag="MeasureDefinitionReference"),
    FragmentReference(tag="MeasurementGroupReference"),
    FragmentReference(tag="MeasurementItemReference"),
    FragmentReference(tag="MeasurementReference"),
    FragmentReference(tag="MeasurementSchemeReference"),
    FragmentReference(tag="MethodologyReference"),
    FragmentReference(tag="MissingValuesDomainReference"),
    FragmentReference(tag="MissingValuesReference"),
    FragmentReference(tag="NCubeGroupReference"),
    FragmentReference(tag="NCubeInstanceReference"),
    FragmentReference(tag="NCubeMeasureDefinitionReference"),
    FragmentReference(tag="NCubeReference"),
    FragmentReference(tag="NCubeSchemeReference"),
    FragmentReference(tag="NumericDomainReference"),
    FragmentReference(tag="NumericRepresentationReference"),
    FragmentReference(tag="OrganizationGroupReference"),
    FragmentReference(tag="OrganizationReference"),
    FragmentReference(tag="OrganizationSchemeReference"),
    FragmentReference(tag="OriginalArchiveOrganizationReference"),
    FragmentReference(tag="OtherMaterialGroupReference"),
    FragmentReference(tag="OtherMaterialReference"),
    FragmentReference(tag="OtherMaterialSchemeReference"),
    FragmentReference(tag="OverriddenCodeReference"),
    FragmentReference(tag="OwnerReference"),
    FragmentReference(tag="ParentClassificationItemReference"),
    FragmentReference(tag="ParentGeographicLevelReference"),
    FragmentReference(tag="PhysicalDataProductReference"),
    FragmentReference(tag="PhysicalInstanceGroupReference"),
    FragmentReference(tag="PhysicalInstanceReference"),
    FragmentReference(tag="PhysicalStructureGroupReference"),
    FragmentReference(tag="PhysicalStructureLinkReference"),
    FragmentReference(tag="PhysicalStructureReference"),
    FragmentReference(tag="PhysicalStructureSchemeReference"),
    FragmentReference(tag="PredecessorReference"),
    FragmentReference(tag="ProcessingEventGroupReference"),
    FragmentReference(tag="ProcessingEventReference"),
    FragmentReference(tag="ProcessingEventSchemeReference"),
    FragmentReference(tag="ProcessingInstructionGroupReference"),
    FragmentReference(tag="ProcessingInstructionReference"),
    FragmentReference(tag="ProcessingInstructionSchemeReference"),
    FragmentReference(tag="PublisherReference"),
    FragmentReference(tag="QualitySchemeReference"),
    FragmentReference(tag="QualityStandardGroupReference"),
    FragmentReference(tag="QualityStandardReference"),
    FragmentReference(tag="QualityStatementGroupReference"),
    FragmentReference(tag="QualityStatementReference"),
    FragmentReference(tag="QuestionBlockReference"),
    FragmentReference(tag="QuestionGridReference"),
    FragmentReference(tag="QuestionGroupReference"),
    FragmentReference(tag="QuestionItemReference"),
    FragmentReference(tag="QuestionMapReference"),
    FragmentReference(tag="QuestionReference"),
    FragmentReference(tag="QuestionSchemeReference"),
    FragmentReference(tag="RecommendedSampleFrameReference"),
    FragmentReference(tag="RecordLayoutGroupReference"),
    FragmentReference(tag="RecordLayoutReference"),
    FragmentReference(tag="RecordLayoutSchemeReference"),
    FragmentReference(tag="RelatedMapReference"),
    FragmentReference(tag="RelatedOtherMaterialReference"),
    FragmentReference(tag="RelatedToReference"),
    FragmentReference(tag="RelationReference"),
    FragmentReference(tag="RepresentationMapReference"),
    FragmentReference(tag="RepresentedVariableGroupReference"),
    FragmentReference(tag="RepresentedVariableReference"),
    FragmentReference(tag="RepresentedVariableSchemeReference"),
    FragmentReference(tag="ResourceObjectReference"),
    FragmentReference(tag="ResourcePackageReference"),
    FragmentReference(tag="ResponseDomainReference"),
    FragmentReference(tag="ResponsibleAgencyReference"),
    FragmentReference(tag="ResponsibleForSamplingReference"),
    FragmentReference(tag="ReviewObjectReference"),
    FragmentReference(tag="SampleFrameReference"),
    FragmentReference(tag="SampleFrameUsedReference"),
    FragmentReference(tag="SampleLocationReference"),
    FragmentReference(tag="SampleReference"),
    FragmentReference(tag="SampleSizeFormulaReference"),
    FragmentReference(tag="SamplingInformationGroupReference"),
    FragmentReference(tag="SamplingInformationSchemeReference"),
    FragmentReference(tag="SamplingPlanImplementedReference"),
    FragmentReference(tag="SamplingPlanReference"),
    FragmentReference(tag="SamplingStageReference"),
    FragmentReference(tag="SamplingUnitReference"),
    FragmentReference(tag="ScaleDomainReference"),
    FragmentReference(tag="ScaleRepresentationReference"),
    FragmentReference(tag="SimilarConceptReference"),
    FragmentReference(tag="SourceClassificationItemReference"),
    FragmentReference(tag="SourceClassificationReference"),
    FragmentReference(tag="SourceFrameReference"),
    FragmentReference(tag="SourceItemReference"),
    FragmentReference(tag="SourceLevelReference"),
    FragmentReference(tag="SourceLinkVariableReference"),
    FragmentReference(tag="SourceLogicalRecordReference"),
    FragmentReference(tag="SourceParameterReference"),
    FragmentReference(tag="SourceSchemeReference"),
    FragmentReference(tag="SourceVariableReference"),
    FragmentReference(tag="SpatialCoverageReference"),
    FragmentReference(tag="StandardWeightReference"),
    FragmentReference(tag="StatisticalClassificationReference"),
    FragmentReference(tag="StudyUnitReference"),
    FragmentReference(tag="SubCategoryReference"),
    FragmentReference(tag="SubUniverseClassReference"),
    FragmentReference(tag="SubclassOfReference"),
    FragmentReference(tag="SuccessorClassificationItemReference"),
    FragmentReference(tag="SuccessorReference"),
    FragmentReference(tag="SummaryDataReference"),
    FragmentReference(tag="TargetClassificationItemReference"),
    FragmentReference(tag="TargetClassificationReference"),
    FragmentReference(tag="TargetItemReference"),
    FragmentReference(tag="TargetLevelReference"),
    FragmentReference(tag="TargetLinkVariableReference"),
    FragmentReference(tag="TargetLogicalRecordReference"),
    FragmentReference(tag="TargetParameterReference"),
    FragmentReference(tag="TargetSchemeReference"),
    FragmentReference(tag="TemporalCoverageReference"),
    FragmentReference(tag="TextDomainReference"),
    FragmentReference(tag="TextRepresentationReference"),
    FragmentReference(tag="ThenConstructReference"),
    FragmentReference(tag="TopLevelReference"),
    FragmentReference(tag="TopicalCoverageReference"),
    FragmentReference(tag="UnitTypeClassifiedReference"),
    FragmentReference(tag="UnitTypeGroupReference"),
    FragmentReference(tag="UnitTypeReference"),
    FragmentReference(tag="UnitTypeSchemeReference"),
    FragmentReference(tag="UniverseGroupReference"),
    FragmentReference(tag="UniverseMapReference"),
    FragmentReference(tag="UniverseReference"),
    FragmentReference(tag="UniverseSchemeReference"),
    FragmentReference(tag="UntilConstructReference"),
    FragmentReference(tag="ValueRepresentationReference"),
    FragmentReference(tag="VariableGroupReference"),
    FragmentReference(tag="VariableMapReference"),
    FragmentReference(tag="VariableReference"),
    FragmentReference(tag="VariableSchemeReference"),
    FragmentReference(tag="VariableStatisticsReference"),
    FragmentReference(tag="VariableUsedReference"),
    FragmentReference(tag="VariableValueReference"),
    FragmentReference(tag="VariantOfReference"),
    FragmentReference(tag="VersionResponsibilityReference"),
    FragmentReference(tag="WeightVariableReference"),
    FragmentReference(tag="WeightingMethodologyReference"),
    FragmentReference(tag="WeightingProcessReference"),
    FragmentReference(tag="WeightingReference"),
    FragmentReference(tag="WhileConstructReference"),
)


__all__ = [
    "FRAGMENT_GENERATED_ENTITIES",
    "FRAGMENT_GENERATED_REFERENCES",
    "FragmentEntity",
    "FragmentReference",
    "IdentifiableKind",
]
