#!/usr/bin/env python3
"""Load LFS DDI into Neo4j, create SDMX 3.0 overlay nodes, and print lineage.

Workflow
--------
1. Load LFS.xml + Ireland_LabourSurvey.xml into Neo4j via DDIFragmentLoader.
2. Parse LFS_DSD.xml (generated by sdmx_from_physical_instance.py) and
   MERGE SDMX 3.0 nodes: SDMXDataStructure, SDMXDimension, SDMXAttribute,
   SDMXCodelist, SDMXConceptScheme.
3. Run DDI → SDMX mapping Cypher queries to build MAPS_TO_SDMX relationships.
4. Print lineage paths and a coverage report.

Usage:
    python load_sdmx_lfs.py

Prerequisites:
    1. Run sdmx_from_physical_instance.py first  (generates LFS_DSD.xml)
    2. Neo4j running with credentials in a .env file or environment variables:
         DDIGRAPH_NEO4J_URI=bolt://localhost:7687
         DDIGRAPH_NEO4J_USER=neo4j
         DDIGRAPH_NEO4J_PASSWORD=your-password
"""

from __future__ import annotations

import asyncio
import re
import sys
from pathlib import Path
from typing import Any

from lxml import etree
from neo4j import AsyncDriver, AsyncGraphDatabase

from ddigraph import DDIFragmentLoader, detect_ddi_format
from ddigraph.config import Settings
from ddigraph.graph.bootstrap import ensure_schema

# ── SDMX ID normalisation (mirrors sdmx_from_physical_instance.py) ───────────

_RE_NON = re.compile(r"[^A-Za-z0-9_-]")
_RE_DUP = re.compile(r"_+")


def _sdmx_id(s: str) -> str:
    clean = _RE_DUP.sub("_", _RE_NON.sub("_", s.upper())).strip("_")
    if clean and clean[0].isdigit():
        clean = "_" + clean
    return clean[:128] or "_UNKNOWN"


# ── SDMX 3.0 namespace map (for parsing LFS_DSD.xml) ─────────────────────────

_SDMX = {
    "mes": "http://www.sdmx.org/resources/sdmxml/schemas/v3_0/message",
    "str": "http://www.sdmx.org/resources/sdmxml/schemas/v3_0/structure",
    "com": "http://www.sdmx.org/resources/sdmxml/schemas/v3_0/common",
}
_XML = "http://www.w3.org/XML/1998/namespace"


# ── Helpers ───────────────────────────────────────────────────────────────────


def _t(elem: etree._Element, path: str) -> str:
    found = elem.find(path, _SDMX)
    return (found.text or "").strip() if found is not None else ""


def _section(title: str) -> None:
    print()
    print("=" * 64)
    print(f"  {title}")
    print("=" * 64)


# ── DSD parser ────────────────────────────────────────────────────────────────


def parse_dsd(dsd_path: Path) -> dict[str, Any]:
    """Return a dict with lists of codelists, dimensions, attributes, measures."""
    tree = etree.parse(str(dsd_path))
    root = tree.getroot()

    dsd_info: dict[str, Any] = {
        "id": "",
        "agency": "",
        "version": "",
        "codelists": [],
        "dimensions": [],
        "attributes": [],
        "measures": [],
    }

    # DataStructure identity
    dsd_e = root.find(".//str:DataStructure", _SDMX)
    if dsd_e is not None:
        dsd_info["id"] = dsd_e.get("id", "")
        dsd_info["agency"] = dsd_e.get("agencyID", "")
        dsd_info["version"] = dsd_e.get("version", "")

    # Codelists
    for cl_e in root.findall(".//str:Codelist", _SDMX):
        dsd_info["codelists"].append(
            {
                "sdmx_id": cl_e.get("id", ""),
                "agency": cl_e.get("agencyID", ""),
                "version": cl_e.get("version", ""),
                "name": _t(cl_e, "str:Name"),
                "n_codes": len(cl_e.findall("str:Code", _SDMX)),
            }
        )

    # Dimensions (TIME_PERIOD handled separately)
    for dim_e in root.findall(".//str:DimensionList/str:TimeDimension", _SDMX):
        dsd_info["dimensions"].append(
            {
                "sdmx_id": dim_e.get("id", ""),
                "position": dim_e.get("position", "1"),
                "variable_name": dim_e.get("id", ""),
                "concept_urn": _t(dim_e, "str:ConceptIdentity"),
                "codelist_urn": "",
                "is_time": True,
            }
        )
    for dim_e in root.findall(".//str:DimensionList/str:Dimension", _SDMX):
        enum_urn = ""
        enum_e = dim_e.find("str:LocalRepresentation/str:Enumeration", _SDMX)
        if enum_e is not None:
            enum_urn = (enum_e.text or "").strip()
        dsd_info["dimensions"].append(
            {
                "sdmx_id": dim_e.get("id", ""),
                "position": dim_e.get("position", ""),
                "variable_name": dim_e.get("id", ""),
                "concept_urn": _t(dim_e, "str:ConceptIdentity"),
                "codelist_urn": enum_urn,
                "is_time": False,
            }
        )

    # Attributes
    for attr_e in root.findall(".//str:AttributeList/str:Attribute", _SDMX):
        tf_e = attr_e.find("str:LocalRepresentation/str:TextFormat", _SDMX)
        tf_type = tf_e.get("textType", "") if tf_e is not None else ""
        dsd_info["attributes"].append(
            {
                "sdmx_id": attr_e.get("id", ""),
                "variable_name": attr_e.get("id", ""),
                "usage_status": attr_e.get("usageStatus", "Conditional"),
                "text_type": tf_type,
                "concept_urn": _t(attr_e, "str:ConceptIdentity"),
            }
        )

    # Measures
    for m_e in root.findall(".//str:MeasureList/str:Measure", _SDMX):
        dsd_info["measures"].append(
            {
                "sdmx_id": m_e.get("id", ""),
                "concept_urn": _t(m_e, "str:ConceptIdentity"),
            }
        )

    return dsd_info


# ── Neo4j SDMX node creation ──────────────────────────────────────────────────


async def create_sdmx_nodes(
    driver: AsyncDriver, database: str, dsd: dict[str, Any]
) -> dict[str, int]:
    """MERGE all SDMX structural nodes derived from the parsed DSD."""
    counts: dict[str, int] = {}

    async with driver.session(database=database) as session:
        # SDMXDataStructure
        await session.run(
            """
            MERGE (d:SDMXDataStructure {sdmx_id: $id})
            SET d.agency_id = $agency,
                d.version   = $version,
                d.source    = 'LFS_DSD.xml'
            """,
            id=dsd["id"],
            agency=dsd["agency"],
            version=dsd["version"],
        )
        counts["SDMXDataStructure"] = 1

        # SDMXCodelist nodes
        for cl in dsd["codelists"]:
            await session.run(
                """
                MERGE (c:SDMXCodelist {sdmx_id: $sdmx_id})
                SET c.agency_id = $agency,
                    c.version   = $version,
                    c.name      = $name,
                    c.n_codes   = $n_codes
                WITH c
                MATCH (d:SDMXDataStructure {sdmx_id: $dsd_id})
                MERGE (d)-[:CONTAINS_CODELIST]->(c)
                """,
                sdmx_id=cl["sdmx_id"],
                agency=cl["agency"],
                version=cl["version"],
                name=cl["name"],
                n_codes=cl["n_codes"],
                dsd_id=dsd["id"],
            )
        counts["SDMXCodelist"] = len(dsd["codelists"])

        # SDMXDimension nodes
        for dim in dsd["dimensions"]:
            await session.run(
                """
                MERGE (dim:SDMXDimension {sdmx_id: $sdmx_id})
                SET dim.position      = $position,
                    dim.variable_name = $variable_name,
                    dim.concept_urn   = $concept_urn,
                    dim.codelist_urn  = $codelist_urn,
                    dim.is_time       = $is_time
                WITH dim
                MATCH (d:SDMXDataStructure {sdmx_id: $dsd_id})
                MERGE (d)-[:HAS_DIMENSION]->(dim)
                """,
                sdmx_id=dim["sdmx_id"],
                position=dim["position"],
                variable_name=dim["variable_name"],
                concept_urn=dim["concept_urn"],
                codelist_urn=dim["codelist_urn"],
                is_time=dim["is_time"],
                dsd_id=dsd["id"],
            )
            # Link dimension to its codelist if one is referenced
            if dim["codelist_urn"]:
                cl_id = (
                    dim["codelist_urn"].split(":")[-1].split("(")[0]
                    if ":" in dim["codelist_urn"]
                    else ""
                )
                if cl_id:
                    await session.run(
                        """
                        MATCH (dim:SDMXDimension {sdmx_id: $dim_id})
                        MATCH (cl:SDMXCodelist   {sdmx_id: $cl_id})
                        MERGE (dim)-[:ENUMERATED_BY]->(cl)
                        """,
                        dim_id=dim["sdmx_id"],
                        cl_id=cl_id,
                    )
        counts["SDMXDimension"] = len(dsd["dimensions"])

        # SDMXAttribute nodes
        for attr in dsd["attributes"]:
            await session.run(
                """
                MERGE (a:SDMXAttribute {sdmx_id: $sdmx_id})
                SET a.variable_name = $variable_name,
                    a.usage_status  = $usage_status,
                    a.text_type     = $text_type,
                    a.concept_urn   = $concept_urn
                WITH a
                MATCH (d:SDMXDataStructure {sdmx_id: $dsd_id})
                MERGE (d)-[:HAS_ATTRIBUTE]->(a)
                """,
                sdmx_id=attr["sdmx_id"],
                variable_name=attr["variable_name"],
                usage_status=attr["usage_status"],
                text_type=attr["text_type"],
                concept_urn=attr["concept_urn"],
                dsd_id=dsd["id"],
            )
        counts["SDMXAttribute"] = len(dsd["attributes"])

        # SDMXMeasure
        for meas in dsd["measures"]:
            await session.run(
                """
                MERGE (m:SDMXMeasure {sdmx_id: $sdmx_id})
                SET m.concept_urn = $concept_urn
                WITH m
                MATCH (d:SDMXDataStructure {sdmx_id: $dsd_id})
                MERGE (d)-[:HAS_MEASURE]->(m)
                """,
                sdmx_id=meas["sdmx_id"],
                concept_urn=meas["concept_urn"],
                dsd_id=dsd["id"],
            )
        counts["SDMXMeasure"] = len(dsd["measures"])

    return counts


# ── DDI → SDMX mapping Cypher queries ────────────────────────────────────────


async def run_mapping_queries(driver: AsyncDriver, database: str) -> dict[str, int]:
    """Link DDI Variable nodes to their SDMX Dimension or Attribute counterparts.

    Variable.name is the raw DDI VariableName; SDMX component IDs are the
    normalised form produced by _sdmx_id().  We pre-compute the mapping in
    Python and pass it to Cypher via UNWIND so every variable is matched
    regardless of case or punctuation differences.
    """
    results: dict[str, int] = {}

    async with driver.session(database=database) as session:
        # Fetch raw DDI variable names and compute their normalised SDMX IDs.
        raw_result = await session.run("MATCH (v:Variable) RETURN v.name AS name")
        raw_records = await raw_result.data()
        pairs = [{"raw": r["name"], "norm": _sdmx_id(r["name"])} for r in raw_records if r["name"]]

        # A — Variable → SDMXDimension
        rec = await (
            await session.run(
                """
            UNWIND $pairs AS p
            MATCH (v:Variable {name: p.raw})
            MATCH (d:SDMXDimension {sdmx_id: p.norm})
            WHERE NOT (v)-[:MAPS_TO_SDMX]->()
            WITH v, d
            MERGE (v)-[r:MAPS_TO_SDMX {component_type: 'Dimension'}]->(d)
            RETURN count(r) AS linked
            """,
                pairs=pairs,
            )
        ).single()
        results["Variable→SDMXDimension"] = rec["linked"] if rec else 0

        # B — Variable → SDMXAttribute
        rec = await (
            await session.run(
                """
            UNWIND $pairs AS p
            MATCH (v:Variable {name: p.raw})
            MATCH (a:SDMXAttribute {sdmx_id: p.norm})
            WHERE NOT (v)-[:MAPS_TO_SDMX]->()
            WITH v, a
            MERGE (v)-[r:MAPS_TO_SDMX {component_type: 'Attribute'}]->(a)
            RETURN count(r) AS linked
            """,
                pairs=pairs,
            )
        ).single()
        results["Variable→SDMXAttribute"] = rec["linked"] if rec else 0

        # C — CodeList (DDI) → SDMXCodelist via the already-established
        #     Variable→SDMXDimension→SDMXCodelist path.
        rec = await (
            await session.run(
                """
            MATCH (v:Variable)-[:USES_CODELIST]->(cl:CodeList)
            MATCH (v)-[:MAPS_TO_SDMX]->(dim:SDMXDimension)-[:ENUMERATED_BY]->(scl:SDMXCodelist)
            WITH cl, scl
            MERGE (cl)-[r:EQUIVALENT_TO]->(scl)
            RETURN count(r) AS linked
            """
            )
        ).single()
        results["DDICodeList→SDMXCodelist"] = rec["linked"] if rec else 0

    return results


# ── Coverage report ────────────────────────────────────────────────────────────


async def coverage_report(driver: AsyncDriver, database: str, dsd: dict[str, Any]) -> None:
    _section("DDI → SDMX COVERAGE REPORT")

    async with driver.session(database=database) as session:
        # Node counts
        rec = await (await session.run("MATCH (n:Variable) RETURN count(n) AS n")).single()
        n_ddi_vars = rec["n"] if rec else 0

        rec = await (
            await session.run(
                "MATCH (v:Variable)-[:MAPS_TO_SDMX]->() RETURN count(DISTINCT v) AS n"
            )
        ).single()
        n_mapped = rec["n"] if rec else 0

        rec = await (
            await session.run(
                "MATCH (v:Variable) WHERE NOT (v)-[:MAPS_TO_SDMX]->() RETURN count(v) AS n"
            )
        ).single()
        n_unmapped = rec["n"] if rec else 0

        n_sdmx_dim = len(dsd["dimensions"])
        n_sdmx_attr = len(dsd["attributes"])

        pct = f"{100 * n_mapped // n_ddi_vars}%" if n_ddi_vars else "—"

        print(f"""
  DDI Variable nodes        : {n_ddi_vars:>6}
  Mapped to SDMX component  : {n_mapped:>6}  ({pct})
  Unmapped                  : {n_unmapped:>6}

  SDMX DSD components
    Dimensions              : {n_sdmx_dim:>6}  (incl. TIME_PERIOD)
    Attributes              : {n_sdmx_attr:>6}
    Codelists               : {len(dsd["codelists"]):>6}
""")

        # Quarter-by-quarter lineage sample
        print("  Lineage sample  PhysicalInstance → DataRelationship → Variable → SDMXComponent")
        print(f"  {'Quarter':<22}  {'Variable':<26}  {'SDMX Type':<16}  {'SDMX ID'}")
        print(f"  {'-' * 22}  {'-' * 26}  {'-' * 16}  {'-' * 30}")

        result = await session.run(
            """
            MATCH (pi:PhysicalInstance)-[:HAS_DATA_RELATIONSHIP]->(dr)
                  -[:USES_VARIABLE]->(v:Variable)
                  -[:MAPS_TO_SDMX]->(comp)
            RETURN dr.name   AS quarter,
                   v.name    AS variable,
                   labels(comp)[0] AS comp_type,
                   comp.sdmx_id    AS sdmx_id
            ORDER BY quarter, variable
            LIMIT 20
            """
        )
        rows = await result.data()
        if rows:
            for row in rows:
                print(
                    f"  {(row['quarter'] or '')[:22]:<22}  "
                    f"{(row['variable'] or '')[:26]:<26}  "
                    f"{(row['comp_type'] or ''):<16}  "
                    f"{row['sdmx_id'] or ''}"
                )
        else:
            print(
                "  (no lineage paths found — PhysicalInstance→DataRelationship graph "
                "may require both files loaded with the same loader instance)"
            )

        # Unmapped sample
        result = await session.run(
            """
            MATCH (v:Variable)
            WHERE NOT (v)-[:MAPS_TO_SDMX]->()
            RETURN v.name AS name, v.label AS label
            ORDER BY name
            LIMIT 10
            """
        )
        unmapped = await result.data()
        if unmapped:
            print("\n  Unmapped Variable sample (no SDMX counterpart):")
            for row in unmapped:
                print(f"    {(row['name'] or '_'):<26}  {(row['label'] or '')[:50]}")

        # Codelist equivalence stats
        rec = await (
            await session.run("MATCH ()-[:EQUIVALENT_TO]->() RETURN count(*) AS n")
        ).single()
        n_equiv = rec["n"] if rec else 0
        print(f"\n  DDICodeList → SDMXCodelist equivalences : {n_equiv}")


# ── Main ──────────────────────────────────────────────────────────────────────


async def main() -> None:
    demo_dir = Path(__file__).parent
    lfs_path = demo_dir / "LFS.xml"
    survey_path = demo_dir / "Ireland_LabourSurvey.xml"
    dsd_path = demo_dir / "LFS_DSD.xml"
    env_file = demo_dir / ".env"

    for p in (lfs_path, survey_path):
        if not p.exists():
            print(f"Error: {p} not found")
            sys.exit(1)

    if not dsd_path.exists():
        print(f"Error: {dsd_path.name} not found.")
        print("  Run sdmx_from_physical_instance.py first to generate it.")
        sys.exit(1)

    settings = Settings(_env_file=env_file) if env_file.exists() else Settings()

    _section("LFS 2020  DDI → Neo4j → SDMX Lineage Graph")

    driver = AsyncGraphDatabase.driver(
        settings.neo4j_uri,
        auth=(settings.neo4j_user, settings.neo4j_password.get_secret_value()),
    )

    try:
        await driver.verify_connectivity()
        print(f"\n  Connected to {settings.neo4j_uri}")

        # ── Step 1: bootstrap schema ─────────────────────────────────────────
        await ensure_schema(driver, database=settings.neo4j_database, include_fragments=True)
        print("  Schema ready")

        # ── Step 2: load DDI files ────────────────────────────────────────────
        # Ireland_LabourSurvey.xml must be loaded first so QuestionItem nodes
        # exist before LFS.xml emits QuestionReference relationships.
        ddi_totals: dict[str, int] = {}
        for path in (survey_path, lfs_path):
            fmt = detect_ddi_format(path)
            print(f"\n  Loading {path.name}  [{fmt}] …")
            loader = DDIFragmentLoader(driver, settings=settings)
            result = await loader.load(path)
            # "relationships"/"batches" are processing meta-stats, not node types.
            meta_keys = {"relationships", "batches"}
            for k, v in result.items():
                ddi_totals[k] = ddi_totals.get(k, 0) + v
                if v > 0 and k not in meta_keys:
                    print(f"    {k}: {v}")
            print(f"    Relationships (edges): {result.get('relationships', 0)}")
        async with driver.session(database=settings.neo4j_database) as session:
            rec = await (await session.run("MATCH (n) RETURN count(n) AS n")).single()
            print(f"\n  Total nodes in database: {rec['n'] if rec else 0}")

        # ── Step 3: parse LFS_DSD.xml ─────────────────────────────────────────
        print(f"\n  Parsing {dsd_path.name} …")
        dsd = parse_dsd(dsd_path)
        print(f"    DataStructure : {dsd['id']} v{dsd['version']}")
        print(f"    Codelists     : {len(dsd['codelists'])}")
        print(f"    Dimensions    : {len(dsd['dimensions'])}")
        print(f"    Attributes    : {len(dsd['attributes'])}")
        print(f"    Measures      : {len(dsd['measures'])}")

        # ── Step 4: create SDMX overlay nodes ────────────────────────────────
        print("\n  Creating SDMX nodes in Neo4j …")
        sdmx_counts = await create_sdmx_nodes(driver, settings.neo4j_database, dsd)
        for label, n in sorted(sdmx_counts.items()):
            print(f"    {label:<24}: {n}")

        # ── Step 5: DDI → SDMX mapping Cypher ────────────────────────────────
        print("\n  Running DDI → SDMX mapping queries …")
        mapping = await run_mapping_queries(driver, settings.neo4j_database)
        for rel, n in mapping.items():
            print(f"    {rel:<35}: {n}")

        # ── Step 6: coverage report + lineage ────────────────────────────────
        await coverage_report(driver, settings.neo4j_database, dsd)

        _section("CYPHER QUERY EXAMPLES")
        print("""
  Paste these into Neo4j Browser to explore the DDI↔SDMX graph:

  -- Variable → SDMX component
  MATCH (v:Variable)-[:MAPS_TO_SDMX]->(c)
  RETURN v.name, labels(c)[0] AS type, c.sdmx_id
  LIMIT 20

  -- Full lineage: PhysicalInstance → DataRelationship → Variable → SDMX
  MATCH path =
    (pi:PhysicalInstance)-[:HAS_DATA_RELATIONSHIP]->(dr)
    -[:USES_VARIABLE]->(v:Variable)
    -[:MAPS_TO_SDMX]->(comp)
  RETURN path LIMIT 50

  -- Codelist bridge: DDI CodeList ↔ SDMX Codelist
  MATCH (cl:CodeList)-[:EQUIVALENT_TO]->(scl:SDMXCodelist)
  RETURN cl.name, scl.sdmx_id, scl.n_codes
  LIMIT 20

  -- Variable linked to question text
  MATCH (v:Variable)-[:REFERENCES_QUESTION]->(q:QuestionItem)
  MATCH (v)-[:MAPS_TO_SDMX]->(c)
  RETURN v.name, q.text, labels(c)[0], c.sdmx_id
  LIMIT 20
""")

    finally:
        await driver.close()


if __name__ == "__main__":
    asyncio.run(main())
